name: 'Code Climate Coverage Action'
description: 'Publish code coverage to Code Climate'
author: 'GP <me@httgp.com>'
branding:
  icon: 'code'
  color: 'gray-dark'
inputs:
  coverageCommand:
    description: 'Coverage command to execute'
    default: 'yarn coverage'
  debug:
    description: 'Enable debugging logs for the Code Climate test reporter'
    default: 'false'
runs:
  using: 'node12'
  main: 'lib/main.js'
